Small functionality updates and minor bug fixes
This addes the following small printer functionalities:

- PRINT_TERM_CONV: the conversion briefly discussed in Zulip
- REMARK_TAC: a tactic version of `remark`

Also this fixes the following small bugs:

(1) `use_file_raise_failure` must reset `loaded_file`.

When `use_file_raise_failure` is used, any failure in the loading files
will lose the defined OCaml bindings so far. This is expected behavior,
but one inconvenience is that the `loaded_file` variable is still correspondingly
updated. This makes the `needs` unable to load the file again.

An example:
```
(* file0.ml *)
loadt "file1.ml";;
loadt "file2.ml";;
(* file1.ml *)
let x = 1;;
(* file2.ml *)
failwith".";;
```

In HOL Light:

```
  # use_file_raise_failure := true;;
  val it : unit = ()
  # loadt "file0.ml";;
  val x : int = 1
  - : unit = ()
  Exception: Failure "fail".
  Exception: Failure "Error in included file /home/aqjune/hol-light/file2.ml".
  Exception: Failure "Error in included file /home/aqjune/hol-light/file0.ml". <-- these tree exceptions are expected
  # loaded_files;;
  val it : (string * Digest.t) list ref =
  {contents =
    [("file1.ml", "D*Ec\003yC@\026u"); <--- this is not expected!
    ...
    ]
```

This makes running `needs "file1.ml";;` again impossible, even if its OCaml bindings have been all dropped.
This happens when loading "{arm,x86}/proofs/base.ml";; with `use_file_raise_failure := true`;; set.
This patch makes `use_file_raise_failure` completely recover `loaded_files`.

(2) Nested `time` was printing weirdly when Exception was happening.

For example, when `time (fun () -> time (fun () -> failwith "aa") ()) ();;` was run,
it was printing something that cannot be unciphered.
After this patch, now it prints ok:
```
  # time (fun () -> time (fun () -> failwith "aa") ()) ();;
  Failed after (user) CPU time of 9.99999997475e-07: Failure("aa")
  Failed after (user) CPU time of 9.29999999926e-05: Failure("aa")
  Exception: Failure "aa".
```