Add support for camlp5 8.03.06
This patch adds support for camlp5 8.03.06.
camlp5 contains an important update for supporting line number directives.
Using a line number directive, a user can describe the current line number on REPL as well as an OCaml source file.
For example, on the REPL, you can track the line number in the stack trace:
```
  # Printexc.record_backtrace true;;

  # #100 "dummy.ml"
    failwith ".";;

    Exception: Failure ".".
    Called from it in file "dummy.ml", line 100, characters 0-12
    Called from unknown location
```
(this is the result on OCaml 5.2 (make switch-5). it seems OCaml 4.14 aggressively drops the stack trace info.
 however, as long as a filename '//toplevel//' doesn't appear it is fine.)
Combined with vscode functionality (https://github.com/monadius/vscode-hol-light/pull/22) this can greatly improve debugging experience.

This also extends the inline_load.ml to insert the line number directives when inlining source files.
This can be checked by printing a parse tree from ocamlc (this will also work on OCaml 4.14):
```
  eval $(opam env) # Load opam switch of this directory
  ocamlc -dparsetree -pp "`./hol.sh -pp`" hol_lib_inlined.ml -o tmp.cmo 2>a.txt
  # a.txt will contain the AST tree with correct source code locations annotated, not just annotated with 'hol_lib_inlined.ml'
```