Added a new Examples file about the NIST-recommended (though see https://eprint.iacr.org/2015/1018.pdf) elliptic curves over prime-order fields, P-384 and friends. This file sets up the parameters for P-192, P-224, P-256, P-384 and P-521, defines those curve groups in affine Weierstrass form, and shows they do indeed form groups and have the orders claimed in the NIST documents; it is also proved here that those orders are prime and hence that the groups are cyclic, plus a few other expected properties of the NIST parameters. This development makes these definitions (mainly NIST parameters plus general elliptic curve stuff):
        b_192
        b_224
        b_256
        b_384
        b_521
        c_192
        c_224
        c_256
        c_384
        c_521
        n_192
        n_224
        n_256
        n_384
        n_521
        p192_group
        p224_group
        p256_group
        p384_group
        p521_group
        p_192
        p_224
        p_256
        p_384
        p_521
        SEED_192
        SEED_224
        SEED_256
        SEED_384
        SEED_521
        weierstrass_add
        weierstrass_curve
        weierstrass_group
        weierstrass_neg
        weierstrass_singular

and proves these theorems:

        FINITE_WEIERSTRASS_CURVE
        CARD_BOUND_WEIERSTRASS_CURVE
        CAUCHY_GROUP_THEOREM_2
        EXCLUDE_ELLIPTIC_CURVE_ROOTS
        FINITE_GROUP_CARRIER_192
        FINITE_GROUP_CARRIER_224
        FINITE_GROUP_CARRIER_256
        FINITE_GROUP_CARRIER_384
        FINITE_GROUP_CARRIER_521
        FINITE_QUADRATIC_CURVE
        GENERATED_P192_GROUP
        GENERATED_P224_GROUP
        GENERATED_P256_GROUP
        GENERATED_P384_GROUP
        GENERATED_P521_GROUP
        GENERATOR_IN_GROUP_CARRIER_192
        GENERATOR_IN_GROUP_CARRIER_224
        GENERATOR_IN_GROUP_CARRIER_256
        GENERATOR_IN_GROUP_CARRIER_384
        GENERATOR_IN_GROUP_CARRIER_521
        GROUP_ADHOC_ORDER_UNIQUE_LEMMA
        GROUP_ELEMENT_ORDER_G192
        GROUP_ELEMENT_ORDER_G224
        GROUP_ELEMENT_ORDER_G256
        GROUP_ELEMENT_ORDER_G384
        GROUP_ELEMENT_ORDER_G521
        G_192
        G_224
        G_256
        G_384
        G_521
        NO_ROOTS_P192
        NO_ROOTS_P224
        NO_ROOTS_P256
        NO_ROOTS_P384
        NO_ROOTS_P521
        P192_GROUP
        P224_GROUP
        P256_GROUP
        P384_GROUP
        P521_GROUP
        PRIME_N192
        PRIME_N224
        PRIME_N256
        PRIME_N384
        PRIME_N521
        PRIME_P192
        PRIME_P224
        PRIME_P256
        PRIME_P384
        PRIME_P521
        PRIME_RULE
        P_192
        P_224
        P_256
        P_384
        P_521
        SANITY_CHECK_192
        SANITY_CHECK_224
        SANITY_CHECK_256
        SANITY_CHECK_384
        SANITY_CHECK_521
        SIZE_P192_GROUP
        SIZE_P224_GROUP
        SIZE_P256_GROUP
        SIZE_P384_GROUP
        SIZE_P521_GROUP
        WEIERSTRASS_ADD_ASSOC
        WEIERSTRASS_ADD_LNEG
        WEIERSTRASS_ADD_SYM
        WEIERSTRASS_CURVE_0
        WEIERSTRASS_CURVE_ADD
        WEIERSTRASS_CURVE_NEG
        WEIERSTRASS_GROUP
        WEIERSTRASS_GROUP_REM

Added quite a few miscellaneous lemmas, mainly to support this
example, in particular, a definition of the ring of integers mod n and
various simple properties of it (defaulting to Z itself for n = 0, by
analogy with groups, since this seems to give the cleanest theorems).
New definition

        integer_mod_ring

and theorems (plus some application-specific conversions and
tactics):

        CARD_INTEGER_MOD_RING
        FIELD_INTEGER_MOD_RING
        FINITE_CARD_LE_IMAGE
        FINITE_CARD_LE_SUBSET
        FINITE_CARD_LE_UNION
        FINITE_CARD_LE_UNIONS
        FINITE_INTEGER_MOD_RING
        FINITE_INTEGRAL_DOMAIN_EQ_FIELD
        FORALL_OPTION_THM
        GROUP_ELEMENT_ORDER_EQ_2_ALT
        GROUP_ELEMENT_ORDER_UNIQUE_PRIME
        INTEGER_MOD_RING
        INTEGER_MOD_RING_ASSOCIATES
        INTEGER_MOD_RING_CHAR
        INTEGER_MOD_RING_DIVIDES
        INTEGER_MOD_RING_OF_INT
        INTEGER_MOD_RING_OF_NUM
        INTEGER_MOD_RING_POW
        INTEGER_MOD_RING_UNIT
        INTEGRAL_DOMAIN_INTEGER_MOD_RING
        INT_LT_REM_EQ
        INT_REM_POS
        INT_REM_POS_EQ
        INVOLUTION_EVEN_FIXPOINTS
        INVOLUTION_EVEN_NOFIXPOINTS
        ORDER_EQ_1
        ORDER_UNIQUE_PRIME
        RING_CHAR_DIVIDES_MUL
        RING_CHAR_DIVIDES_PRIME
        RING_INV_0
        TRIVIAL_INTEGER_MOD_RING
        ZERO_ONE_OR_PRIME
        ZERO_ONE_OR_PRIME_DIVPROD
        option_DISTINCT
        option_INJ

Also added new "backchaining" rules and tactics to automate ring
carrier membership (RING_CARRIER_RULE and RING_CARRIER_TAC), and moved
a few existing rules and lemmas (MOD_DOWN_CONV, INT_REM_DOWN_CONV,
coprime and GCD) back into the basic core from other Library files
since they seem too generally useful. Two of the added lemmas above,
INVOLUTION_EVEN_FIXPOINTS and INVOLUTION_EVEN_NOFIXPOINTS, are in
effect factored out of the existing Zagier-style "one-sentence"
proofs in 100/two_squares.ml and 100/four_squares.ml, which now make
use of them.

Finally, improved the ring-specific Groebner procedure by preserving
variable naming when totalizing in INTEGRAL_DOMAIN_RULE, as well as
making a more far-reaching bugfix to the generic Groebner procedure
which previously did not handle pure refutation over a non-field in
the most effective way. In cases where there are no negated equations
(i.e. you are originally just trying to refute a set of equations, not
show that some other equation follows from them), it tries to replay
the proof directly rather than go via the circuitous (and sometimes
very inefficient) route of computing the cofactors explicitly, doing
the weak->strong Nullstellensatz transform etc. But this does not in
general work if there are non-integer constants in the trace, e.g.

  # INT_RING `&3 * x + &1:int  = &0 /\ &7 * x = &43 ==> F`;;
  1 basis elements and 0 critical pairs
  Exception: Failure "integer argument required".

Changed this so that unless the Rabinowitsch theorem provided is
non-trivial, it will do a more careful "scaled" version of proof
replay. The above now works, and refutation in non-field integral
domains (or ostensible ones, i.e. fields where the field properties
aren't supplied to the generic procedure) can often become more
efficient as a result since they don't need to go through the
lengthier path. Also added a more informative message about how the
proof generation is done, so you get exactly one of

 "Translating certificate to HOL inferences"    (cofactor certificate)
 "Generating HOL version of proof"              (direct proof replay)
 "Generating HOL version of scaled proof"       (integer-scaled proof replay)