Fix tactics in impconv.ml to raise Failure rather than Unchanged
Tactics in impconv.ml may raise `Unchanged` rather than `Failure` if they fail.
This makes `ORELSE` unable to use because `ORELSE` only catches `Failure` but not `Unchanged`:

```
 # g `1 + 1 = 2`;;
val it : goalstack = 1 subgoal (1 total)

`1 + 1 = 2`

 # e(IMP_REWRITE_TAC[MOD_LT] ORELSE ARITH_TAC);;
Exception: Unchanged.
```

This patch fixes the tactics to raise `Failure` to enable this.