Allow benign redefinition in new_inductive_definition when extra foralls are added
This patch extends `new_inductive_definition` to support benign redefinition
when `new_inductive_definition` has to add extra universally quantified variables to the
specification.

An example is `steps` in s2n-bignum:

```
 # new_inductive_definition `(!s. steps (step:S->S->bool) 0 (s:S) (s:S)) /\
     (!s s'' n. (?s'. step s s' /\ steps step n s' s'') ==> steps step (n+1) s s'')`;;
 val it : thm * thm * thm =
    (|- forall step.
            (forall s. steps step 0 s s) /\
            (forall s s'' n.
                 (exists s'.
                      step s s' /\
                      steps step n s' s'')
                 ==> steps step (n + 1) s s''),
     |- forall step steps'.
            (forall s. steps' 0 s s) /\
            (forall s s'' n.
                 (exists s'.
                      step s s' /\
                      steps' n s' s'')
                 ==> steps' (n + 1) s s'')
            ==> (forall a0 a1 a2.
                     steps step a0 a1 a2
                     ==> steps' a0 a1 a2),
     |- forall step a0 a1 a2.
            steps step a0 a1 a2 <=>
            a0 = 0 /\ a2 = a1 \/
            (exists n.
                 a0 = n + 1 /\
                 (exists s'.
                      step a1 s' /\
                      steps step n s' a2)))
 # new_inductive_definition `(!s. steps (step:S->S->bool) 0 (s:S) (s:S)) /\
     (!s s'' n. (?s'. step s s' /\ steps step n s' s'') ==> steps step (n+1) s s'')`;;
 Exception: Failure "dest_var: not a variable".
```

This is failing because `new_inductive_definition` internally adds extra quantified variables, specifically
the `step` variable (the fourth line of the above output).
To fix this, this patch adds a fix using `PART_MATCH` which is analogous to what `define` in define.ml
does.