Print "'name' is already defined" message
This updates `new_basic_definition` and `define` to print "'name' is already defined" error message if the constant already exists.
This also makes `new_definition` print the message because it internally calls `new_basic_definition`.

```
\# new_basic_definition `x=10`;;
val it : thm = |- x = 10
\# new_basic_definition `x=20`;;
Exception: Failure "new_basic_definition: 'x' is already defined".
\# new_definition `x=20`;;
Exception: Failure "new_basic_definition: 'x' is already defined".
\# define `x=30`;;
Exception: Failure "define: 'x' is already defined".
```

Three more definition functions (`new_recursive_definition`, `new_inductive_definition` and `new_specification`) are not updated in this patch.
I avoided touching them because their implementations look complicated to me. :/